# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HSFCircleMenuDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HSFCircleMenuDemo

  target 'HSFCircleMenuDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HSFCircleMenuDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  
  pod 'Masonry'#布局
  pod 'TYAlertController'#提示框
  pod 'IQKeyboardManager'#键盘
  

end
